### ISSUE TITLE
Close buttons are missing

### ISSUE THREAD

**Issue by tekvsakdan** [nsz32/docklike-plugin#100]
I installed xfce4-docklike-plugin in Xubuntu 21.04 via repository ppa:xubuntu-dev/extras.
Current installed version is 0.0-git20210427.6ac5b37-0ppa1-21.04. Version 0.2.0 is installed.

Now I have missing close buttons everywhere. How can I fix that? I install all Noto fonts as described in #85 and it didn't work.

![image](https://user-images.githubusercontent.com/620899/119628470-6d262200-be0d-11eb-95b7-8938ad47a412.png)

**Comment by davekeogh** [comment]
Hi, Can you confirm if this is fixed in my branch?
https://github.com/davekeogh/xfce4-docklike-plugin

If so, I will create a PR for this issue.

**Comment by SwampRabbit** [comment]
@davekeogh I'm been using your branch since the last commit on 27 April, and its doing the same thing.
I only have fonts-noto and fonts-noto-core installed.

Note: although the icon is wrong, clicking it still works.

**Comment by davekeogh** [comment]
Could someone post the terminal output from running the panel in debug mode? Make sure you open this menu at least once and the bug occurs.

Example:
`xfce4-panel -q`
`PANEL_DEBUG=1 xfce4-panel`

**Comment by unit193** [comment]
@davekeogh ppa:xubuntu-dev/extras is actually currently on your fork, that commit hash should be latest master.

**Comment by SwampRabbit** [comment]
@davekeogh here ya go.
[docklike-debug.txt](https://github.com/nsz32/docklike-plugin/files/6582396/docklike-debug.txt)

Let me know if you need anything else.  Might not respond super fast, but I'll try.

**Comment by davekeogh** [comment]
This should be fixed with this commit: https://github.com/davekeogh/xfce4-docklike-plugin/commit/f8c7699b1d27987d1b0033fa7c68dc57e2c325d1
Let me know if this works.

**Comment by SwampRabbit** [comment]
@davekeogh I'll build it later today and give it a go.

**Comment by tekvsakdan** [comment]
It is working now. The x-icon is now visible.

**Comment by SwampRabbit** [comment]
@davekeogh apologies on the delay, can confirm the package builds fine, and the icon rendering is now corrected.
