### ISSUE TITLE
Unknown License

### ISSUE THREAD

**Issue by Qrbaker** [nsz32/docklike-plugin#111]
Hi, I'm working on making a FreeBSD port of this plugin but I don't know what license should be used, as it is not specified. Could you consider adding a `LICENSE` file (e.g. [like the xfce one](https://gitlab.xfce.org/xfce/xfce4-panel/-/blob/master/COPYING)) to the repository?

**Comment by nsz32** [comment]
GPL3, free as in freedom :)

**Comment by Qrbaker** [comment]
Thanks!
