### ISSUE TITLE
Problem installing on Debian XFCE

### ISSUE THREAD

**Issue by MLito747** [nsz32/docklike-plugin#123]
![image](https://user-images.githubusercontent.com/94821482/146330830-38a0327d-b64b-4c64-9fad-2b18ad4e4184.png)
I've manually installed libwnck-3.0 like three times already with `sudo apt-get install -y libwnck-3-0` and it still shows up that error.
Thanks

**Comment by hexdsl** [comment]
same issue here. same output,

**Comment by tgerov** [comment]
Try `sudo apt-get install libwnck-3-dev`

**Comment by MLito747** [comment]
Thanks for the answer, but i couldn't test that since i moved to Void (Best choice i've made in 2021, it's been 3 hours tryna build this). Should i close this issue?

**Comment by hexdsl** [comment]
I can confirm that this worked. I now have this installed and working correctly on 3 machines. Thank you. (did not know there was a dev package for this, sorry)
