### ISSUE TITLE
This plugin does not work with ubuntu xfce.

### ISSUE THREAD

**Issue by creeper-0910** [nsz32/docklike-plugin#15]
Hello.
I tried to build this plugin with xfce on ubuntu, but the plugin wasn't visible and couldn't be used.
Is there a way to fix this strange behavior?
Thank you!

**Comment by nsz32** [comment]
Did the plugin shows in the "Elements Add" list from the xfce panel ?

**Comment by creeper-0910** [comment]
The files used are:
  libxfce4panel-2.0-dev
  libxfce4ui-2-dev
  cairo-5c
libwnck-3-dev
But it does not appear in the list.
Is this wrong?

**Comment by nsz32** [comment]
This is the compilation/installation script I use for devel :
`sudo echo
echo Compilation ...
make -j4
if [ $? -eq 0 ]; then
	echo
	echo Installation ...
	sudo cp src/.libs/libdocklike.so /usr/lib/xfce4/panel/plugins/
	sudo cp docklike.desktop /usr/share/xfce4/panel/plugins/
fi`

Before trying to launch it in a dock-line clone folder, please check the two destination folders. Theese can change from distro to another.

**Comment by creeper-0910** [comment]
Good work, thank you.
But the storage location looks the same.
I don't know the difference.
"sudo cp docklike.desktop /usr/share/xfce4/panel/plugins/"
Not enough here?

**Comment by nsz32** [comment]
Did you clone the git repository before build it ?
Please use these commands :
```
git clone https://github.com/nsz32/docklike-plugin
cd docklike-plugin
./autogen.sh
make
sudo make install
```

**Comment by creeper-0910** [comment]
I did the same. But,
"sudo cp docklike.desktop /usr/share/xfce4/panel/plugins/"
is I think it wasn't running.

**Comment by nsz32** [comment]
I don't know if you can run the plugin or not.

**Comment by creeper-0910** [comment]
I'm sorry, my native language is not English, so it may be difficult to understand.
It worked fine with the above script, but when compared to autorun.sh,
"sudo cp docklike.desktop /usr/share/xfce4/panel/plugins/"
Did not seem to be running.

**Comment by nsz32** [comment]
It's `make install` that run the two file copy form installation.
`autogen.sh` generates all configuration files to prepare for compilation.
Closed as it's working for you.

**Comment by creeper-0910** [comment]
I got it. Thank you.
