### ISSUE TITLE
Isolate windows by active workspace.

### ISSUE THREAD

**Issue by nervecenter** [nsz32/docklike-plugin#16]
Requesting a feature much like KDE or Dash to Panel whereby active window buttons can be isolated by workspace. Switching workspaces changes the taskbar state depending on what is in that workspace. If windows are there, they show and stack. Otherwise, even a pinned app shows as inactive, and clicking it should open a new window.

**Comment by nsz32** [comment]
:+1:

**Comment by davekeogh** [comment]
Thanks for getting this merged. I've been using this for the past couple of days and it works perfectly with my workflow.
