### ISSUE TITLE
[Feature Request] Color Selection

### ISSUE THREAD

**Issue by droided4u** [nsz32/docklike-plugin#18]
This is by far the best window manager plugin. It's very well made. Thank you for your work.
Right clicking for launch another is a bit more work than i would like, can we have a combination like on plank? Can be Super+Left click as well.

Another feature could be adding color selection of some sort. Though it does get the job done with almost any color scheme, it looks a bit off on light color schemes. Not my problem though, i'm more into dark themes.

**Comment by nsz32** [comment]
Thanks ! Glad you like it !

Ctrl+LeftClick worked as you intended since my April upgrades. It's a regression.
I will try to fix it tomorrow.

Yes, color selection could be very nice. I will think about it.

**Comment by nsz32** [comment]
The color feature is very interesting to me.
It's should be implemented prior to anything when I have time.

Thank you,

**Comment by nsz32** [comment]
Color chooser is now implemented
