### ISSUE TITLE
New Instance

### ISSUE THREAD

**Issue by vinox14** [nsz32/docklike-plugin#19]
I'm not sure if it's by design or an issue, when I for example minimize an app and open another instance using shift + left mouse button it'll open another but will also restore the one previously minimized. Unlike when I use the right click context menu of the plugin it just opens another instance without restoring the minimized one.
Thank you for this app. just ditched the one (dockbarx) I previously use because this consumes half the ram compared to it, this really fits the XFCE desktop environment for it's simplicity and lightness.

**Comment by nsz32** [comment]
You are right, this is not the expected behavior : it shouldn't restore minimized windows when we launch a new instance with shift+leftclick
I will fix it pretty soon
Merci

**Comment by nsz32** [comment]
28d9a0c restore the correct behavior of the shift new instance
Just recompile your plugin,

**Comment by vinox14** [comment]
thank you!!!
