### ISSUE TITLE
Build/install on Xubuntu 20.04

### ISSUE THREAD

**Issue by tobcro** [nsz32/docklike-plugin#20]
Hi,
I have tried to build and install DockLike on a bare Xubuntu 20.04. Fixed all dependencies but the plugin is not seen by "Add new items" in the panel preferences. I am guessing that make and make install is installing them in the wrong (for Ubuntu) locations, and tried moving files to where the other plugins are located but no success. Does anyone have any idea how to solve this?

**Comment by nsz32** [comment]
Here is the script I use to build and install the plugin during development (on ArchLinux) :

> sudo echo
> echo Compilation ...
> make -j4
> if [ $? -eq 0 ]; then
>         echo
>         echo Installation ...
>         sudo cp src/.libs/libdocklike.so /usr/lib/xfce4/panel/plugins/
>         sudo cp docklike.desktop /usr/share/xfce4/panel/plugins/
> fi

The two last `cp` are for plugin installation. Please check these two destination paths to match with your system.
If these paths are different from mine, please just let me know.

**Comment by tobcro** [comment]
Thank you for your help! I used this script and it worked 👍 Just the panel plugin I have been missing for XFCE, great work!

**Comment by kamferdrops** [comment]
Same with Debian Buster: 

> Fixed all dependencies but the plugin is not seen by "Add new items" in the panel preferences.

“<i>Libdocklike.la</i>” and “<i>libdocklike.so</i>» are placed “_/usr<b>/local</b>/lib/xfce4/panel/plugins/_” instead of in “_/usr/lib/xfce4/panel/plugins/_”.

“_docklike.desktop_» is placed in “_/usr<b>/local</b>/share/xfce4/panel/plugins/_” instead of in “_/usr/share/xfce4/panel/plugins/_”.

Also, when I copy the files to the same directories as nsz32s script use the plugin works but shows up as to instances in “_add new items_” in the xfce panel preference.

**Comment by nsz32** [comment]
> but shows up as two instances in “add new items” in the xfce panel preference.
Have you deleted the docklike.desktop file in /usr/local/share/xfce4/panel/plugins/ ? This can cause the two instances issue.
I will update the installation script. Thank for your feedback

**Comment by kamferdrops** [comment]
> Have you deleted the docklike.desktop file in /usr/local/share/xfce4/panel/plugins/ ? Two .desktop files can cause the two instances issue.
@nsz32 : You're right. Moving the files instead of copying it fixed that. Thanks a lot.

**Comment by nsz32** [comment]
d54e7ce uses now global (not local path) for installation and solves this issue
Ty,
