### ISSUE TITLE
Sometimes i have to click unminimise to raise windows back.

### ISSUE THREAD

**Issue by droided4u** [nsz32/docklike-plugin#21]
Manjaro Linux.
xfce4-panel -V
xfce4-panel 4.14.4 (Xfce 4.14)

Sometimes windows are bugged and I cannot raise them. I need to right click and select unminimise from context menu.
Have no clue how to reproduce the problem. But it happens pretty often. Probably when a window is in a busy state or something. For example, I was just installing an app using pamac, while it was installing I switched to another screen and the bug happened.

Thanks for sharing your work, it definitely is the best window manager plugin for Xfce panel.

**Comment by nsz32** [comment]
This should now be fixed by cb2b2ea . Please tell me if not.
