### ISSUE TITLE
xfdesktop crashes?

### ISSUE THREAD

**Issue by vinox14** [nsz32/docklike-plugin#22]
open up xfdesktop-settings (right click - desktop settings), minimize it by clicking its icon on the panel then clicking it again.
wallpaper disappears and only way to bring it back is to kill xfdesktop in the taskmanager.

**Comment by nsz32** [comment]
Commit 7c73c03 should solve the crashes. Please tell me if not.
Thanks for the feedback.

**Comment by vinox14** [comment]
> Commit [7c73c03](https://github.com/nsz32/docklike-plugin/commit/7c73c03e8a59d8cb113b0b506ed9bb08c6020620) should solve the crashes. Please tell me if not.
> (crashes happened when trying to raise the xfdesktop window)
> Thanks for the feedback.

thank you!!! it's all fine now
