### ISSUE TITLE
Can I fork it?

### ISSUE THREAD

**Issue by rilian-la-te** [nsz32/docklike-plugin#26]
I want to do it multi-panel, can I fork this?

**Comment by rilian-la-te** [comment]
It is GPL-3.0, so, I cannot( (Need LGPL) Sorry for disturbance.

**Comment by nsz32** [comment]
What do you understand by multi-panel ? For me it means multi-intance and it is already possible.

I would say that you can fork my plugin if you want (why not ?) : you just need to keep my name associated with my work.
And if you are nice, please just let me a pull request to integrate you contribution.
