### ISSUE TITLE
LibreOffice icon

### ISSUE THREAD

**Issue by Hayao0819** [nsz32/docklike-plugin#32]
The LibreOffice icon is not displayed properly.
libxfce4ui, libxfce4util, and thunar are proprietary packages that are newer than the official Arch Linux repositories.

```
$ yay -Q | grep xfce
libxfce4ui 4.15.3-1
libxfce4util 4.15.1-2
xfce4-appfinder 4.14.0-2
xfce4-calculator-plugin 0.7.0-1
xfce4-clipman-plugin 1.6.1-1
xfce4-dev-tools 4.14.0-2
xfce4-docklike-plugin-git 20200914-1
xfce4-mount-plugin 1.1.3-2
xfce4-notifyd 0.6.2-2
xfce4-panel 4.14.4-1
xfce4-panel-profiles 1.0.10-1
xfce4-power-manager 1.6.6-1
xfce4-pulseaudio-plugin 0.4.3-1
xfce4-screenshooter 1.9.7-2
xfce4-session 4.14.2-2
xfce4-settings 4.14.3-1
xfce4-terminal 0.8.9.2-1
xfce4-verve-plugin 2.0.0-2
xfce4-whiskermenu-plugin 2.4.6-1
```

![image](https://user-images.githubusercontent.com/32128205/93712714-80079900-fb92-11ea-854c-b9a3a56c201c.png)

**Comment by nsz32** [comment]
I'm installing libreO to solve this.
Can't understand `libxfce4ui, libxfce4util, and thunar are proprietary packages that are newer than the official Arch Linux repositories.`

**Comment by nsz32** [comment]
Ok, it's a limitation of WNCK the lib used to get window's informations and associate them with a .desktop file.
We need here to move to another lib, BAMF which is more accurate.
This is related to #14 and maybe can solve #13 too.
Give me some time.

**Comment by nsz32** [comment]
Can't understand `libxfce4ui, libxfce4util, and thunar are proprietary packages that are newer than the official Arch Linux repositories.`

**Comment by Hayao0819** [comment]
Sorry, I am not good at Engliah.
I created my own PKGBUILD based it of Arch Linux official because I want to use a newer version of Thunar than the official Arch Linux repository.  I'm afraid that this version difference may be causing the bug.
However, if my interpretation of your text is correct, it is not the bug for the difference of the version.

**Comment by nsz32** [comment]
Please check 20ad936

**Comment by nsz32** [comment]
Libreoffice is now supported
