### ISSUE TITLE
About Docklike Taskbar

### ISSUE THREAD

**Issue by Hayao0819** [nsz32/docklike-plugin#34]
The lines of contributors are unnaturally broken.
At first I thought this was a mistake in Japanese translation, but it happened in English as well.

![image](https://user-images.githubusercontent.com/32128205/93840500-949b7c80-fccb-11ea-98ae-b07aa9f0cf2e.png)

**Comment by nsz32** [comment]
It's the about dialog that only has a field "Created By" and doesn't have a "Contributors" field.
The "Contributors:" you see here is one line in the "Created By" field.
xfce4-clipman-plugin does the exact same thing.
ty,
