### ISSUE TITLE
Feature Request: Indicator position when panel is in deskbar mode

### ISSUE THREAD

**Issue by vinox14** [nsz32/docklike-plugin#37]
Would it be possible for the indicator to shift it's position for example to the left of a pinned/opened application when the panel is in deskbar mode on left side of the screen. I think it would look much nicer that way esp. the dot indicator.

**Comment by nsz32** [comment]
ACK

**Comment by nsz32** [comment]
Hey, hope 1db0366 responds well to your request !

**Comment by vinox14** [comment]
very nice!!! thank you!!!
