### ISSUE TITLE
Multiple panel/screen issues

### ISSUE THREAD

**Issue by davekeogh** [nsz32/docklike-plugin#39]
- Moving a window between screens more than once will cause it to lose the active indicator
- If you have window on each screen from the same app and you right click on the inactive one's dock item, the plugin will crash

The second one is pretty major, I think this may be due to the WnckMenu still being attached to the other dock. Any ideas?

**Comment by davekeogh** [comment]
Thank you. Both issues are fixed with these changes.

**Comment by davekeogh** [comment]
I spoke too soon. This actually introduces an issue where the active indicator persists after closing all instances of an application now.

Example: I have Chrome pinned. If I have a window on both monitors and then close all Chrome windows, the active indicator remains.

**Comment by nsz32** [comment]
How did you close all windows ? By the "Close all" menu ?
Is the active indicator grey or colored ? Where does it remains ? Both screen ?
Please speak with Screen1 / Screen2, where window is active before, how is it closed etc.

Sorry, i don't have two screens so, please be precise, ty,

**Comment by davekeogh** [comment]
The grey highlight was remaining on both screens.
