### ISSUE TITLE
Can't build for xfce4.14 with Ubuntu 18.04

### ISSUE THREAD

**Issue by diogofd8** [nsz32/docklike-plugin#41]
Hello! 
I tried compilling but came up with an error like this: 
```
checking for gtk+-3.0 >= 3.24.0... found, but 3.22.30
*** The required package gtk+-3.0 was found on your system,
*** but the installed version (3.22.30) is too old.
*** Please upgrade gtk+-3.0 to atleast version 3.24.0, or adjust
*** the PKG_CONFIG_PATH environment variable if you installed
*** the new version of the package in a nonstandard prefix so
*** pkg-config is able to find it.
```

I manually upgraded xfce4.12 to 4.14 a while ago, that's probably why the latest version of libgtk3 is 3.22.30 while it is asking for 3.24 which would be from Ubuntu 20.04. What can I do? I wish there was a deb repository

**Comment by nsz32** [comment]
I can't guarantee you it will work then, but this is only a package check issue.
You can try to edit `configure.ac.in` and change the required version at line 61 :
`XDT_CHECK_PACKAGE([GTK], [gtk+-3.0], [3.24.0])` -> `XDT_CHECK_PACKAGE([GTK], [gtk+-3.0], [3.22.0])` 
Recompile starting with step `./autogen.sh`. Do this again if another package hangs (it will happens probably with cairo).
Keep me informed.

**Comment by diogofd8** [comment]
`dnl ***********************************
dnl *** Check for required packages ***
dnl ***********************************
XDT_CHECK_LIBX11_REQUIRE()
XDT_CHECK_PACKAGE([GIO], [gio-2.0], [2.42.0])
XDT_CHECK_PACKAGE([GLIB], [glib-2.0], [2.42.0])
XDT_CHECK_PACKAGE([GTK], [gtk+-3.0], [3.22.0])
XDT_CHECK_PACKAGE([CAIRO], [cairo], [1.15.0])
XDT_CHECK_PACKAGE([WNCK], [libwnck-3.0], [3.24.1])
XDT_CHECK_PACKAGE([X11], [x11], [1.6])
XDT_CHECK_PACKAGE([LIBXFCE4UI], [libxfce4ui-2], [4.14.0])
XDT_CHECK_PACKAGE([LIBXFCE4UTIL], [libxfce4util-1.0], [4.14.0])
XDT_CHECK_PACKAGE([LIBXFCE4PANEL], [libxfce4panel-2.0], [4.14.0])`

Edited the checks to this, it ran till the end.
But then the make command gave the following error (dunno if related)

```
Makefile:673: recipe for target 'libdocklike_la-Helpers.lo' failed
make[1]: *** [libdocklike_la-Helpers.lo] Error 1
make[1]: Leaving directory '/home/user/git/docklike-plugin/src'
Makefile:478: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by davekeogh** [comment]
It looks like the G_SOURCE_FUNC macro wasn't added until glib 2.58 which isn't in 18.04.

Try replacing line 164 of Helpers.cpp w/ this and see if it builds:

`			mTimeoutId = g_timeout_add(mDuration, (GSourceFunc) (+[](Timeout* me) {`

**Comment by diogofd8** [comment]
Worked like a charm!
