### ISSUE TITLE
Right clicking on an item for a steam game will crash the plugin

### ISSUE THREAD

**Issue by davekeogh** [nsz32/docklike-plugin#45]
I noticed this will a couple of steam games.

**Comment by nsz32** [comment]
Can you send me a xprop of one of these windows please ?
Very interesting !

**Comment by davekeogh** [comment]
https://gist.github.com/davekeogh/7dc61062ff369bb79eeb55cd56c237e3
https://gist.github.com/davekeogh/a3524506a9dc42c84ece415caa4d2c7f

Here's the xprop output from two that will always cause the plugin to crash (on my machine at least).

**Comment by nsz32** [comment]
Are these windows identified by the plugin ? Do they have an icon ?

**Comment by davekeogh** [comment]
They both have the generic application-executable icon from my icon theme.

**Comment by davekeogh** [comment]
This actually has nothing to do with these being fullscreen apps and seems to happen with any steam games. Sorry. 

Maybe this has something to do with them not having an associated .desktop file?

**Comment by nsz32** [comment]
You got it.
I solved this issue some times ago, it seems it need actualization.
