### ISSUE TITLE
Can you add support for ubuntu 18.04?

### ISSUE THREAD

**Issue by denisgolius** [nsz32/docklike-plugin#52]
Hello!
Can you add support for ubuntu 18.04?

```
root@ryzen:/tmp/docklike-plugin# ./autogen.sh
xdt-autogen: This version of xdt-autogen (4.12.0) is too old.
             Version 4.14.0 or greater is required.
```

**Comment by nsz32** [comment]
Duplicate of #41 , check it for compilation instructions.
Maybe should we include this changes in the repo ?

**Comment by gsantner** [comment]
@nsz32 I made a PR at #66 that covers both issues. With it the plugin runs on my XFCE 4.12 + Ubuntu 18.04.
