### ISSUE TITLE
No Terminal Icon

### ISSUE THREAD

**Issue by Goatmaster** [nsz32/docklike-plugin#58]
Hey,

 I use Xubuntu.

The installation was no problem. But I have the wrong Icon shown for my terminal application.
I use the Papirus icon theme, also when I switch the icon theme it shows the wrong icon for terminal.

Here is a screenshot.
[https://i.imgur.com/gAqgsOC.png](https://i.imgur.com/gAqgsOC.png)

**Comment by joisaac** [comment]
I've got the same problem, it also happens with WPS documents

**Comment by lavalampa** [comment]
+1 Same goes for GNOME Evolution

**Comment by nsz32** [comment]
Xubuntu each ?
Please check #44

**Comment by nsz32** [comment]
The plugin should ignore any incomplete .desktop files

**Comment by nsz32** [comment]
Please someone to keep the bug in place, without applying #44 workaround.
I will patch the code to bypass any incomplete .desktop files tomorrow.
Need one to confirm it solve this.

**Comment by nsz32** [comment]
Try with e76a5ea

**Comment by lavalampa** [comment]
Works

**Comment by nsz32** [comment]
Nice, closing
