### ISSUE TITLE
Crash on multiple displays

### ISSUE THREAD

**Issue by Hayao0819** [nsz32/docklike-plugin#61]
I use this plugin in the panel on the sub-display and it crashes repeatedly when I open multiple apps.

Specifically, display two Xfce4-terminal windows on both the sub-display and the main display, and after using Xfce's default window switch on the main display, this plugin on the sub-display will display the terminal window. Crashes when switching.

I have "Show only applications from the current display" enabled.

**Comment by julien-maurel** [comment]
Hi, Same issue as here, #49

**Comment by nsz32** [comment]
dup #49
