### ISSUE TITLE
vala?

### ISSUE THREAD

**Issue by aleex5** [nsz32/docklike-plugin#7]
After trying and seeing the plugin's approach, I think it would be a good idea to use vala
whenever I used gtk3 + vala, I have always seen good performance and fluency, it is one of my favorite combinations

in the desks that I had the opportunity to see in action "vala", was when I used "pantheon desktop" (elementary os) and budgie
and even in PC of low resources they were decent
in fact budgie applets use "vala", that's why it consumes few resources

so consider it

**Comment by nsz32** [comment]
I tried months ago an panel-plugin on vala and wasn't able to get it working.
Please submit me a working minimal panel-plugin with makefile. Thx

**Comment by aleex5** [comment]
could use as an example the plugin "vala-panel-appmenu-xfce-git" that is in the aur, uses few dependencies, like its plugin
is the only one that occurs to me that is for xfce

the problem is that I'm not a developer, if not, I would have gladly helped you, I love your plugin

**Comment by win10-ToZ-FreewheelinFrank** [comment]
> good that its fixed
 ya i glitch it out so i can talk... DONT FIX BUG GITHUB
