### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by fyr77** [nsz32/docklike-plugin#8]
Sometimes when applications which are not pinned are opened, they're missing their icons. I do not know what causes this, since it's not always the same applications. 
A reboot seems to change the behaviour with different applications missing their icons.

I am running XFCE-Panel 4.12.

![lWmy16E](https://user-images.githubusercontent.com/8578362/62006840-8644e580-b146-11e9-8a19-7bc460fde3d3.png)

**Comment by mnnyang** [comment]
I also encountered this problem and some icons were lost.

**Comment by nsz32** [comment]
I know about this problem.
It occurs when no .desktop file is associated with the launched application.

Three cases:
1. the application has just been installed and docklike did not load the .desktop file (is done at launch)
Restart the panel or the plugin should solve the issue.
The solution in code is to check for new .desktop files

2. the .desktop file is not associable (exotic application)
This needs to code an exotic association with the application (see ADDIT in source)

3. the .desktop file is missing
The only solution is to take the window icon.
This last case poses several issues : application not pinable, icon can change according to the active window

As you have noticed, I do not currently have the time to code these changes.
It will be done in a more or less near future, and your feedback helps me find out what is this most urgent.

Thanks,

**Comment by nsz32** [comment]
Mnnyang, what do you mean by "some icons were lost" ?

Did you lost your pinned applications ?
It can be possible if you delete the plugin and recreate one.

Loosing icon on pinned app should not be possible unless you change the icon theme of your system.

If this isn't your case, please try to give me a step-to-reproduce about it.

**Comment by mnnyang** [comment]
Thank you very much, it has been solved according to the solution you gave.

**Comment by mnnyang** [comment]
> Mnnyang, what do you mean by "some icons were lost" ?
> 
> Did you lost your pinned applications ?
> It can be possible if you delete the plugin and recreate one.
> 
> Loosing icon on pinned app should not be possible unless you change the icon theme of your system.
> 
> If this isn't your case, please try to give me a step-to-reproduce about it.



> Mnnyang, what do you mean by "some icons were lost" ?
> 
> Did you lost your pinned applications ?
> It can be possible if you delete the plugin and recreate one.
> 
> Loosing icon on pinned app should not be possible unless you change the icon theme of your system.
> 
> If this isn't your case, please try to give me a step-to-reproduce about it.

Thank you very much, it has been solved according to the solution you gave.

**Comment by nsz32** [comment]
You're welcome.
Tout ce qui n'est pas partagé est perdu.

**Comment by fyr77** [comment]
I think this issue can be closed, your first answer also solved my question. 
Thank you!
