### ISSUE TITLE
docklike has no way to set default pinned apps

### ISSUE THREAD

**Issue by dolphinoracle** [nsz32/docklike-plugin#87]
for a distro to utilize docklike by default it would be good to be able to set default pinned apps.  right now existing docklike-*.rc files are ignored on first launch.

**Comment by davekeogh** [comment]
Hi. Thanks for the report. Try the pull request out if you like. The plugin will look for a file `XDG_CONFIG_DIRS/xfce4/panel/docklike.rc` for a default file.

**Comment by dolphinoracle** [comment]
that works pretty good thank you.  one other thing... if you remove the docklike plugin from the panel, then it deletes the existing user configuration rather than reuse it later.

**Comment by davekeogh** [comment]
That's by design. Each rc file is tied to an instance of the plugin and there can be several.

**Comment by dolphinoracle** [comment]
Ok then the patch  works to bring in defaults.
