### ISSUE TITLE
feature request: hotkeys to launch applications

### ISSUE THREAD

**Issue by 20NE** [nsz32/docklike-plugin#9]
with this feature, docklike-plugin almost perfect.

B,S:
In Arch linux, is **xfce4-dev-tools** a really needed Dependency after built? 

Cheer.

**Comment by nsz32** [comment]
You are right, xfce4-dev-tools should be a build dependency only.

I think hotkeys are somewhat out of spot as the dock gives you "hotkeys under the mouse".
Also, you can already launch applications from hotkeys with this xfce keyboard settings.
Managing theese hotkeys from docklike would be a cool feature for sure.

Thank for your idea
Marked as enhancement,

**Comment by 20NE** [comment]
Yes, using the shortcut to launch an app, If the app already launched,  just bring that app up instead of opening a new one, that is the one of few things win7 do it right.

You might like to have a  look at **xfce4-taskbar-plugin**

this feature will make docklike standing out from  **plank** **xfce4-dockbarx-plugin**

**Comment by nsz32** [comment]
This is implemented now !
Looking for feedbacks ;)

**Comment by rauldipeas** [comment]
Unity, DockbarX and Dash to panel are using _Super+Numkey_ to launch pinned apps.

**Comment by 20NE** [comment]
> Unity, DockbarX and Dash to panel are using _Super+Numkey_ to launch pinned apps.

What's I don't like about Dockbarx: bloating, made by python2.
Never use the other two.

**Comment by 20NE** [comment]
wooow, you made it,  Super+Numkey work flawlessly.

**Comment by nsz32** [comment]
The super key alone feature use a specific X11 extension.
I wonder and hope this will work on other distros than Arch.

**Comment by 20NE** [comment]
I'm Arch user, but docklike already awesome. Congratulation.
