### ISSUE TITLE
Compiling on Fedora 34 fails

### ISSUE THREAD

**Issue by lig** [nsz32/docklike-plugin#91]
Steps to reproduce:
* install latest Fedora in a VM using one of XFCE spin images from here https://dl.fedoraproject.org/pub/fedora/linux/development/34/Spins/x86_64/iso/ and update using dnf
* git clone the repo ( have the `0022a3fa0c8ba2043ed8dd43017e95043ad21f31` revision checked out)
* install packages using dnf: make xfce4-dev-tools libxfce4ui-devel xfce4-panel-devel autoconf gcc gcc-c++ libtool m4 libwnck3-devel cairo-devel gtk3-devel
* run `./autogen.sh`
* run `make`

Multiple errors of this kind:
```
/usr/include/c++/11/type_traits:2900:3: error: template with C linkage
 2900 |   template<typename _Fn, typename... _Args>
      |   ^~~~~~~~
In file included from Dock.cpp:7:
Dock.hpp:10:1: note: ‘extern "C"’ linkage started here
   10 | extern "C"
      | ^~~~~~~~~~
```

Log [make.log.gz](https://github.com/nsz32/docklike-plugin/files/6079614/make.log.gz)

**Comment by davekeogh** [comment]
Thank you for the bug report. I'll try to investigate this on the weekend. I don't have time to set up a virtual machine to test this right now.

@nsz32 Any idea what's causing this? It looks like the compiler thinks a C++ template is being used within the extern "C" block? I'm not familiar with this stuff.

**Comment by lig** [comment]
@davekeogh I've tried to remove `extern "C"` as suggested in an answer on SO and that allowed me to build the thing. However, XFCE reported that it was constantly restarting. I haven't got more time to test it after that.

Btw, it took me around 10 minutes to set up Fedora 34 VM using Boxes on Fedora 33.

**Comment by davekeogh** [comment]
Hi. Try the version from my branch please.
https://github.com/davekeogh/xfce4-docklike-plugin

I think this is because these spins are using gcc 11 which isn't in any other distros yet. There are few changes to default behaviour that must be causing this error.

**Comment by lig** [comment]
@davekeogh It works! Builds, installs, and works. Thanks a lot!

**Comment by lig** [comment]
@davekeogh I see PR closed but it looks like it wasn't merged. So, the main branch still doesn't compile.
