### ISSUE TITLE
Build fails on Arch Linux in chroot environment

### ISSUE THREAD

**Issue by Hayao0819** [nsz32/docklike-plugin#93]
When I run yay in a chroot environment and build it, it outputs a large amount of logs different from before and terminates abnormally.
However, it builds successfully in my main Arch Linux environment. Is this a problem with my chroot environment? Or is it a software bug? Other software builds will succeed normally in a chroot environment.
[xfce4-docklike-plugin-git.log](https://github.com/nsz32/docklike-plugin/files/6179320/xfce4-docklike-plugin-git.log)

**Comment by Hayao0819** [comment]
You can reproduce it by following the steps below.

```bash
mkdir -p ~/arch
cd ~/arch
mkdir mount
truncate -s 32G -- "arch.img"
mkfs.ext4 -O '^has_journal,^resize_inode' -E 'lazy_itable_init=0' -m 0 -F -- "arch.img" 32G
tune2fs -c "0" -i "0" "arch.img"
sudo mount ./arch.img ./mount
sudo pacstrap ./mount base base-devel go git
sudo arch-chroot ./mount
useradd -s /bin/bash -m user
echo -e "foo\nfoo" | passwd user
echo "user ALL=(ALL) NOPASSWD:ALL" > "/etc/sudoers.d/user"
su user
cd
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si --noconfirm
yay -Sy
yay -S xfce4-docklike-plugin-git --noconfirm
```

**Comment by joaodriessen** [comment]
I get the same errors here building on arch arm armv7h (raspberry pi 3B+)

**Comment by Hayao0819** [comment]
This problem seems to be the same problem as #91
